"""e3 calendar sync metadata

Revision ID: e219fe464c61
Revises: d5941a2a82ff
Create Date: 2026-08-09 07:07:12.688145
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e219fe464c61"
down_revision: str | None = "d5941a2a82ff"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calendar_source", sa.Column("sync_token_query_key", sa.String(length=64), nullable=True)
    )
    op.add_column(
        "calendar_source", sa.Column("last_full_sync_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("calendar_source", "last_full_sync_at")
    op.drop_column("calendar_source", "sync_token_query_key")
    # ### end Alembic commands ###
