"""e2_domain_schema

Revision ID: d5941a2a82ff
Revises: 0001_e1_baseline
Create Date: 2026-08-08 23:58:20.248636
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d5941a2a82ff"
down_revision: str | None = "0001_e1_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guild_config",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("admin_role_id", sa.BigInteger(), nullable=True),
        sa.Column("team_mod_role_id", sa.BigInteger(), nullable=True),
        sa.Column("publisher_role_id", sa.BigInteger(), nullable=True),
        sa.Column("announcement_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("command_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("moderator_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("projects_category_id", sa.BigInteger(), nullable=True),
        sa.Column("archive_category_id", sa.BigInteger(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("publication_weekday", sa.SmallInteger(), nullable=False),
        sa.Column("publication_time", sa.Time(), nullable=False),
        sa.Column("automatic_publication_enabled", sa.Boolean(), nullable=False),
        sa.Column("publish_google_descriptions", sa.Boolean(), nullable=False),
        sa.Column("generated_intro_enabled", sa.Boolean(), nullable=False),
        sa.Column("everyone_mention_enabled", sa.Boolean(), nullable=False),
        sa.Column("closing_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "publication_weekday BETWEEN 0 AND 6", name=op.f("ck_guild_config_publication_weekday")
        ),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_guild_config")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("actor_user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("object_type", sa.String(length=100), nullable=False),
        sa.Column("object_id", sa.String(length=160), nullable=False),
        sa.Column("before_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("result", sa.String(length=24), nullable=False),
        sa.Column("correlation_id", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("result IN ('succeeded', 'failed')", name=op.f("ck_audit_log_result")),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_audit_log_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index("ix_audit_log_correlation", "audit_log", ["correlation_id"], unique=False)
    op.create_index(
        "ix_audit_log_guild_created", "audit_log", ["guild_id", "created_at"], unique=False
    )
    op.create_index("ix_audit_log_object", "audit_log", ["object_type", "object_id"], unique=False)
    op.create_table(
        "calendar_source",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("external_calendar_id", sa.String(length=512), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("sync_token", sa.Text(), nullable=True),
        sa.Column("sync_status", sa.String(length=24), nullable=False),
        sa.Column("last_sync_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sync_status IN ('never', 'running', 'succeeded', 'failed')",
            name=op.f("ck_calendar_source_sync_status"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_calendar_source_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calendar_source")),
        sa.UniqueConstraint(
            "guild_id", "provider", "external_calendar_id", name="calendar_identity"
        ),
    )
    op.create_index(
        "ix_calendar_source_guild_active_priority",
        "calendar_source",
        ["guild_id", "active", "priority"],
        unique=False,
    )
    op.create_table(
        "channel_archive_request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("original_channel_name", sa.String(length=100), nullable=False),
        sa.Column("archive_category_id", sa.BigInteger(), nullable=False),
        sa.Column("requested_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("decided_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("discord_approval_message_id", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'approved', 'rejected', 'expired', 'executed', 'failed')",
            name=op.f("ck_channel_archive_request_state"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_channel_archive_request_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_channel_archive_request")),
    )
    op.create_index(
        "ix_channel_archive_request_state_expires",
        "channel_archive_request",
        ["state", "expires_at"],
        unique=False,
    )
    op.create_index(
        "uq_channel_archive_request_pending_channel",
        "channel_archive_request",
        ["guild_id", "discord_channel_id"],
        unique=True,
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.create_table(
        "info_announcement",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("link_url", sa.String(length=2048), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "valid_until >= valid_from", name=op.f("ck_info_announcement_validity_order")
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_info_announcement_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_info_announcement")),
    )
    op.create_index(
        "ix_info_announcement_guild_active_validity",
        "info_announcement",
        ["guild_id", "active", "valid_from", "valid_until"],
        unique=False,
    )
    op.create_table(
        "manual_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("link_url", sa.String(length=2048), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(is_all_day AND starts_on IS NOT NULL AND ends_on IS NOT NULL "
            "AND starts_at IS NULL AND ends_at IS NULL AND ends_on > starts_on) OR "
            "(NOT is_all_day AND starts_at IS NOT NULL AND starts_on IS NULL "
            "AND ends_on IS NULL AND (ends_at IS NULL OR ends_at > starts_at))",
            name=op.f("ck_manual_event_time_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_manual_event_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_manual_event")),
    )
    op.create_index(
        "ix_manual_event_guild_active_starts_at",
        "manual_event",
        ["guild_id", "active", "starts_at"],
        unique=False,
    )
    op.create_index(
        "ix_manual_event_guild_active_starts_on",
        "manual_event",
        ["guild_id", "active", "starts_on"],
        unique=False,
    )
    op.create_table(
        "publication_run",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("slot_key", sa.String(length=160), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(length=24), nullable=False),
        sa.Column("initiated_by_user_id", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=160), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("mode IN ('automatic', 'manual')", name=op.f("ck_publication_run_mode")),
        sa.CheckConstraint(
            "state IN ('preparing', 'publishing', 'succeeded_automatic', "
            "'succeeded_manual', 'skipped_after_manual', 'failed', "
            "'retry_pending', 'partially_published')",
            name=op.f("ck_publication_run_state"),
        ),
        sa.CheckConstraint("attempt >= 1", name=op.f("ck_publication_run_positive_attempt")),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_publication_run_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_run")),
        sa.UniqueConstraint("guild_id", "slot_key", name="guild_slot"),
        sa.UniqueConstraint("idempotency_key", name="idempotency_key"),
    )
    op.create_index(
        "ix_publication_run_state_scheduled",
        "publication_run",
        ["state", "scheduled_for"],
        unique=False,
    )
    op.create_table(
        "reaction_config",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("seen_enabled", sa.Boolean(), nullable=False),
        sa.Column("seen_emoji_id", sa.BigInteger(), nullable=True),
        sa.Column("seen_emoji_unicode", sa.String(length=32), nullable=True),
        sa.Column("auto_reaction_enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_reaction_emoji_id", sa.BigInteger(), nullable=True),
        sa.Column("auto_reaction_emoji_unicode", sa.String(length=32), nullable=True),
        sa.Column("mention_reaction_enabled", sa.Boolean(), nullable=False),
        sa.Column("mention_reaction_emoji_id", sa.BigInteger(), nullable=True),
        sa.Column("mention_reaction_emoji_unicode", sa.String(length=32), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_reaction_config_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("guild_id", name=op.f("pk_reaction_config")),
    )
    op.create_table(
        "web_session",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_user_id", sa.BigInteger(), nullable=False),
        sa.Column("session_token_hash", sa.String(length=128), nullable=False),
        sa.Column("csrf_token_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_web_session_guild_id_guild_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_web_session")),
        sa.UniqueConstraint("session_token_hash", name="session_token_hash"),
    )
    op.create_index(
        "ix_web_session_expires_revoked", "web_session", ["expires_at", "revoked_at"], unique=False
    )
    op.create_table(
        "event_series_override",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("calendar_source_id", sa.UUID(), nullable=False),
        sa.Column("series_key", sa.String(length=64), nullable=False),
        sa.Column("effective_from_key", sa.String(length=128), nullable=False),
        sa.Column("effective_all_day", sa.Boolean(), nullable=False),
        sa.Column("effective_from_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_from_date", sa.Date(), nullable=True),
        sa.Column("public_title", sa.String(length=1024), nullable=True),
        sa.Column("description_state", sa.String(length=32), nullable=False),
        sa.Column("public_description", sa.Text(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(description_state = 'custom' AND public_description IS NOT NULL) OR "
            "(description_state <> 'custom' AND public_description IS NULL)",
            name=op.f("ck_event_series_override_description_value"),
        ),
        sa.CheckConstraint(
            "description_state IN ('inherit', 'custom', 'intentionally_empty')",
            name=op.f("ck_event_series_override_description_state"),
        ),
        sa.CheckConstraint(
            "(effective_all_day AND effective_from_date IS NOT NULL "
            "AND effective_from_at IS NULL) OR (NOT effective_all_day "
            "AND effective_from_at IS NOT NULL AND effective_from_date IS NULL)",
            name=op.f("ck_event_series_override_effective_shape"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_event_series_override_positive_version")),
        sa.ForeignKeyConstraint(
            ["calendar_source_id"],
            ["calendar_source.id"],
            name=op.f("fk_event_series_override_calendar_source_id_calendar_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_event_series_override")),
        sa.UniqueConstraint(
            "calendar_source_id", "series_key", "effective_from_key", name="series_effective"
        ),
    )
    op.create_index(
        "ix_event_series_override_lookup",
        "event_series_override",
        ["calendar_source_id", "series_key", "effective_from_at", "effective_from_date"],
        unique=False,
    )
    op.create_table(
        "external_event",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("calendar_source_id", sa.UUID(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("provider_event_id", sa.String(length=1024), nullable=False),
        sa.Column("occurrence_id", sa.String(length=1024), nullable=True),
        sa.Column("series_key", sa.String(length=64), nullable=True),
        sa.Column("original_start_key", sa.String(length=128), nullable=True),
        sa.Column("source_title", sa.String(length=1024), nullable=True),
        sa.Column("source_description", sa.Text(), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("source_timezone", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("etag", sa.String(length=512), nullable=True),
        sa.Column("provider_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('confirmed', 'tentative', 'cancelled')",
            name=op.f("ck_external_event_status"),
        ),
        sa.CheckConstraint(
            "(is_all_day AND starts_on IS NOT NULL AND ends_on IS NOT NULL "
            "AND starts_at IS NULL AND ends_at IS NULL AND ends_on > starts_on) OR "
            "(NOT is_all_day AND starts_at IS NOT NULL AND starts_on IS NULL "
            "AND ends_on IS NULL AND (ends_at IS NULL OR ends_at > starts_at))",
            name=op.f("ck_external_event_time_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["calendar_source_id"],
            ["calendar_source.id"],
            name=op.f("fk_external_event_calendar_source_id_calendar_source"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_external_event")),
        sa.UniqueConstraint("source_key", name="source_key"),
    )
    op.create_index(
        "ix_external_event_series_original",
        "external_event",
        ["calendar_source_id", "series_key", "original_start_key"],
        unique=False,
    )
    op.create_index(
        "ix_external_event_source_deleted_starts_at",
        "external_event",
        ["calendar_source_id", "deleted_at", "starts_at"],
        unique=False,
    )
    op.create_index(
        "ix_external_event_source_deleted_starts_on",
        "external_event",
        ["calendar_source_id", "deleted_at", "starts_on"],
        unique=False,
    )
    op.create_table(
        "integration_task",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("calendar_source_id", sa.UUID(), nullable=True),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("deduplication_key", sa.String(length=160), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("leased_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'running', 'succeeded', 'failed', 'retry_pending')",
            name=op.f("ck_integration_task_state"),
        ),
        sa.CheckConstraint("attempt >= 0", name=op.f("ck_integration_task_nonnegative_attempt")),
        sa.ForeignKeyConstraint(
            ["calendar_source_id"],
            ["calendar_source.id"],
            name=op.f("fk_integration_task_calendar_source_id_calendar_source"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["guild_config.guild_id"],
            name=op.f("fk_integration_task_guild_id_guild_config"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_task")),
        sa.UniqueConstraint("guild_id", "task_type", "deduplication_key", name="deduplication"),
    )
    op.create_index(
        "ix_integration_task_state_scheduled",
        "integration_task",
        ["state", "scheduled_for"],
        unique=False,
    )
    op.create_table(
        "publication_message",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_run_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("discord_channel_id", sa.BigInteger(), nullable=False),
        sa.Column("discord_message_id", sa.BigInteger(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('pending', 'sent', 'failed')", name=op.f("ck_publication_message_state")
        ),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_publication_message_nonnegative_position")
        ),
        sa.ForeignKeyConstraint(
            ["publication_run_id"],
            ["publication_run.id"],
            name=op.f("fk_publication_message_publication_run_id_publication_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_message")),
        sa.UniqueConstraint("discord_channel_id", "discord_message_id", name="discord_message"),
        sa.UniqueConstraint(
            "publication_run_id", "position", name="publication_message_run_position"
        ),
    )
    op.create_table(
        "reaction_config_channel",
        sa.Column("guild_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("discord_channel_id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["guild_id"],
            ["reaction_config.guild_id"],
            name=op.f("fk_reaction_config_channel_guild_id_reaction_config"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "guild_id", "discord_channel_id", name=op.f("pk_reaction_config_channel")
        ),
    )
    op.create_table(
        "event_override",
        sa.Column("external_event_id", sa.UUID(), nullable=False),
        sa.Column("public_title", sa.String(length=1024), nullable=True),
        sa.Column("description_state", sa.String(length=32), nullable=False),
        sa.Column("public_description", sa.Text(), nullable=True),
        sa.Column("inclusion_decision", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_by_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(description_state = 'custom' AND public_description IS NOT NULL) OR "
            "(description_state <> 'custom' AND public_description IS NULL)",
            name=op.f("ck_event_override_description_value"),
        ),
        sa.CheckConstraint(
            "description_state IN ('inherit', 'custom', 'intentionally_empty')",
            name=op.f("ck_event_override_description_state"),
        ),
        sa.CheckConstraint(
            "inclusion_decision IN ('auto', 'force_include', 'force_exclude')",
            name=op.f("ck_event_override_inclusion_decision"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_event_override_positive_version")),
        sa.ForeignKeyConstraint(
            ["external_event_id"],
            ["external_event.id"],
            name=op.f("fk_event_override_external_event_id_external_event"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("external_event_id", name=op.f("pk_event_override")),
    )
    op.create_table(
        "publication_item",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("publication_run_id", sa.UUID(), nullable=False),
        sa.Column("item_type", sa.String(length=32), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("external_event_id", sa.UUID(), nullable=True),
        sa.Column("manual_event_id", sa.UUID(), nullable=True),
        sa.Column("info_announcement_id", sa.UUID(), nullable=True),
        sa.Column("final_title", sa.String(length=1024), nullable=True),
        sa.Column("final_description", sa.Text(), nullable=True),
        sa.Column("display_time", sa.String(length=200), nullable=True),
        sa.Column("day_emoji", sa.String(length=200), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("starts_on", sa.Date(), nullable=True),
        sa.Column("ends_on", sa.Date(), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=True),
        sa.Column("link_url", sa.String(length=2048), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "item_type IN ('intro', 'info', 'external_event', 'manual_event', 'outro')",
            name=op.f("ck_publication_item_item_type"),
        ),
        sa.CheckConstraint("position >= 0", name=op.f("ck_publication_item_nonnegative_position")),
        sa.ForeignKeyConstraint(
            ["external_event_id"],
            ["external_event.id"],
            name=op.f("fk_publication_item_external_event_id_external_event"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["info_announcement_id"],
            ["info_announcement.id"],
            name=op.f("fk_publication_item_info_announcement_id_info_announcement"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["manual_event_id"],
            ["manual_event.id"],
            name=op.f("fk_publication_item_manual_event_id_manual_event"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["publication_run_id"],
            ["publication_run.id"],
            name=op.f("fk_publication_item_publication_run_id_publication_run"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publication_item")),
        sa.UniqueConstraint("publication_run_id", "position", name="publication_item_run_position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publication_item")
    op.drop_table("event_override")
    op.drop_table("reaction_config_channel")
    op.drop_table("publication_message")
    op.drop_index("ix_integration_task_state_scheduled", table_name="integration_task")
    op.drop_table("integration_task")
    op.drop_index("ix_external_event_source_deleted_starts_on", table_name="external_event")
    op.drop_index("ix_external_event_source_deleted_starts_at", table_name="external_event")
    op.drop_index("ix_external_event_series_original", table_name="external_event")
    op.drop_table("external_event")
    op.drop_index("ix_event_series_override_lookup", table_name="event_series_override")
    op.drop_table("event_series_override")
    op.drop_index("ix_web_session_expires_revoked", table_name="web_session")
    op.drop_table("web_session")
    op.drop_table("reaction_config")
    op.drop_index("ix_publication_run_state_scheduled", table_name="publication_run")
    op.drop_table("publication_run")
    op.drop_index("ix_manual_event_guild_active_starts_on", table_name="manual_event")
    op.drop_index("ix_manual_event_guild_active_starts_at", table_name="manual_event")
    op.drop_table("manual_event")
    op.drop_index("ix_info_announcement_guild_active_validity", table_name="info_announcement")
    op.drop_table("info_announcement")
    op.drop_index(
        "uq_channel_archive_request_pending_channel",
        table_name="channel_archive_request",
        postgresql_where=sa.text("state = 'pending'"),
    )
    op.drop_index("ix_channel_archive_request_state_expires", table_name="channel_archive_request")
    op.drop_table("channel_archive_request")
    op.drop_index("ix_calendar_source_guild_active_priority", table_name="calendar_source")
    op.drop_table("calendar_source")
    op.drop_index("ix_audit_log_object", table_name="audit_log")
    op.drop_index("ix_audit_log_guild_created", table_name="audit_log")
    op.drop_index("ix_audit_log_correlation", table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("guild_config")
    # ### end Alembic commands ###
